### ISSUE TITLE
Inability to filter messages,via commands

### ISSUE THREAD

**Issue by skx** [Perl-Email-Project/Email-Filter#1]
Although your `Email::Filter` library has all the obvious primitives I'm thinking there is an omission - which is the ability to filter a mail via an external binary.

For example the CRM114 mail filter will run against a mail and output an updated message.  Something like this:

```
    steve@ssh ~ $ /usr/bin/crm -u /home/steve/.crm /usr/share/crm114/mailreaver.crm < Test.mail 
    To: foo@bar.com
    From: steve@steve.com
    Subject: UNS: Hello
    X-CRM114-Version: 20100106-BlameMichelson ( TRE 0.8.0 (BSD) ) MR-27CA1CFB 
    X-CRM114-CacheID: sfid-20140306_154124_764652_540A67EC 
    X-CRM114-Status: UNSURE (   0.02  )
```

As you can see the output is an updated message.

Now I see I can access the input message via `$obj->simple()->as_string()`, and then construct a new `Email::Simple` object which I pass back to `$obj->simple()`, but it seems like it would be more natural to have a `sub filter( cmd )` method.

Does that seem like a reasonable suggestion?

**Comment by rjbs** [comment]
This seems reasonable, and would not disrupt the library's precious purity of essence.
